
language: php

php:
  - 5.6
  - hhvm
  - 7.0
  - 7.1
  - 7.2
  - nightly

env:
  - PHPUNIT=true

dist: trusty
sudo: required

cache:
  directories:
    ${HOME}/bitcoin

matrix:
  exclude:
    # add extra test runs for php7: coverage, codestyle, examples, rpc tests
    - php: 7.0
      env: PHPUNIT=true
  include:
    # add extra test runs for php7: coverage, codestyle, examples, rpc tests
    - php: 7.0
      env: PHPUNIT=true COVERAGE=true CODE_STYLE=true

install:
    - composer update

before_script:
  - if [ "${COVERAGE}" != "true" ] && [ "$TRAVIS_PHP_VERSION" != "hhvm" ] && [ "$TRAVIS_PHP_VERSION" != "nightly" ]; then phpenv config-rm xdebug.ini && echo "xdebug disabled"; fi

script:
  - make phpunit-ci
  - if [ "$CODE_STYLE" = "true" ]; then make phpcs && echo "Code style OK"; fi
  - if [ "$EXAMPLES" = "true" ]; then tools/validate_examples.sh && echo "Examples OK"; fi

after_script:
  - if [ "${COVERAGE}" = "true" ]; then make scrutinizer; fi
